---
# uyuni_server_installation/tasks/main.yml

- name: 'Add Uyuni repository'
  zypper_repository:
    repo: "{{ uyuni_repo }}"
    name: 'uyuni-server-stable'
    state: 'present'
    auto_import_keys: 'yes'
    runrefresh: 'yes'
  when: 'ansible_distribution == "openSUSE Leap" and ansible_distribution_major_version|int == 15'

- name: 'Install package patterns-uyuni_server'
  zypper:
    name: "{{ uyuni_package }}"
    state: 'latest'
  when: 'ansible_distribution == "openSUSE Leap" and ansible_distribution_major_version|int == 15'
